/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ejerciciorecumarzo;

import DAO.DAOPersonas;
import Excepciones.ExcepcionInsertVacio;
import java.util.List;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anton
 */
public class principal extends javax.swing.JFrame {

    DAOPersonas daopersonas = new DAOPersonas();
    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        cargarTablaPersonas();
        daopersonas.cargarComboBox(comboBoxPersonas);
    }
    
    public void cargarTablaPersonas(){
        try{
            ResultSet resultset = daopersonas.getPersonas();

        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        
        Object[] registroLeido = new Object[2];
        while(resultset.next()) {
            registroLeido[0] = resultset.getInt("idpersona");
            registroLeido[1] = resultset.getString("nombre");
                        
            modelo.addRow(registroLeido);
        }
        tablaPersonas.setModel(modelo);
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }
    
    public void cargarTablaVivienda(){
        try{
            ResultSet resultset = daopersonas.getViviendas();

        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("IDVivienda");
        modelo.addColumn("Direccion");
        modelo.addColumn("Numero");
        modelo.addColumn("Es Chungo");
        modelo.addColumn("IDPersona");
        
        Object[] registroLeido = new Object[5];
        while(resultset.next()) {
            registroLeido[0] = resultset.getInt("idvivienda");
            registroLeido[1] = resultset.getString("direccion");
            registroLeido[2] = resultset.getInt("numero");
            registroLeido[3] = resultset.getInt("esChungo");
            registroLeido[4] = resultset.getInt("idpersona");
                        
            modelo.addRow(registroLeido);
        }
        tablaVivienda.setModel(modelo);
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPersonas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        botonInsertar = new javax.swing.JButton();
        textID = new javax.swing.JTextField();
        textIDVivienda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonBorrar = new javax.swing.JButton();
        botonModificarVivienda = new javax.swing.JButton();
        comboBoxPersonas = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista = new javax.swing.JTextArea();
        botonListado = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaVivienda = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textNumero = new javax.swing.JTextField();
        textDireccion = new javax.swing.JTextField();
        textZonaChunga = new javax.swing.JTextField();
        botonBorrarVivienda = new javax.swing.JButton();
        botonModificar1 = new javax.swing.JButton();
        botonInsertarVivienda = new javax.swing.JButton();
        textIDPersona1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        botonNuevaVentana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPersonas);

        jLabel1.setText("PRUEBA REPASO EXAM RECU MARZO");

        botonInsertar.setText("INSERTAR PERSONA");
        botonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarActionPerformed(evt);
            }
        });

        jLabel2.setText("IDPersona: ");

        jLabel3.setText("Nombre:");

        botonBorrar.setText("BORRAR PERSONA");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        botonModificarVivienda.setText("MODIFICAR VIVIENDA");
        botonModificarVivienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarViviendaActionPerformed(evt);
            }
        });

        comboBoxPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboBoxPersonasMouseClicked(evt);
            }
        });

        lista.setColumns(20);
        lista.setRows(5);
        jScrollPane2.setViewportView(lista);

        botonListado.setText("LISTADO ORDENADO POR NOMBRES");
        botonListado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListadoActionPerformed(evt);
            }
        });

        tablaVivienda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaVivienda);

        jLabel4.setText("IDVivienda: ");

        jLabel5.setText("Direccion: ");

        jLabel6.setText("Numero: ");

        jLabel7.setText("Zona Chunga:");

        botonBorrarVivienda.setText("BORRAR VIVIENDA");
        botonBorrarVivienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarViviendaActionPerformed(evt);
            }
        });

        botonModificar1.setText("MODIFICAR PERSONA");
        botonModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonInsertarVivienda.setText("INSERTAR VIVIENDA");
        botonInsertarVivienda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInsertarViviendaActionPerformed(evt);
            }
        });

        jLabel8.setText("IDPersonaVivienda:");

        botonNuevaVentana.setText("Ir Nueva Ventana");
        botonNuevaVentana.setActionCommand("");
        botonNuevaVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaVentanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(botonNuevaVentana))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonInsertar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonBorrar)
                                .addGap(90, 90, 90)
                                .addComponent(comboBoxPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(textNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(textIDVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(textZonaChunga, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(botonModificar1))))
                                .addGap(135, 135, 135))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(botonModificarVivienda))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(textIDPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonInsertarVivienda)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonBorrarVivienda)))
                                .addGap(99, 99, 99)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonListado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))))
                .addGap(0, 107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonNuevaVentana)
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(botonListado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrar)
                    .addComponent(botonInsertar))
                .addGap(18, 18, 18)
                .addComponent(botonModificar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textIDVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(textDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(textNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(textZonaChunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(textIDPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonInsertarVivienda)
                            .addComponent(botonBorrarVivienda))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModificarVivienda))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarActionPerformed
        String idString = textID.getText();
        try{
            if(idString.isEmpty()) {
                throw new ExcepcionInsertVacio();
            } else{
                int id = Integer.parseInt(idString);
                String nombre = textNombre.getText();
                daopersonas.insertarPersona(id, nombre);
                cargarTablaPersonas();
                limpiarTexts();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());        }   
    }//GEN-LAST:event_botonInsertarActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
         int fila = tablaPersonas.getSelectedRow();
            if (fila != -1) {
                int id = Integer.parseInt(tablaPersonas.getValueAt(fila, 0).toString());
                String nombre = tablaPersonas.getValueAt(fila, 1).toString();

                int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres borrar la persona?", "Confirmar Borrado", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                daopersonas.borrarPersona(id, nombre);
                cargarTablaPersonas();
                limpiarTexts();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una categoría para borrar.", "Error", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonModificarViviendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarViviendaActionPerformed
        int filaSeleccionada = tablaVivienda.getSelectedRow();
        if (filaSeleccionada != -1) {
            int idAnterior = Integer.parseInt(tablaVivienda.getValueAt(filaSeleccionada, 0).toString());
            int nuevoId = Integer.parseInt(textIDVivienda.getText());
            String direccion = textDireccion.getText();
            int numero = Integer.parseInt(textNumero.getText());
            boolean esChungo = Boolean.parseBoolean(textZonaChunga.getText());
            int idpersona = Integer.parseInt(textIDPersona1.getText());

            daopersonas.modificarVivienda(idAnterior, nuevoId, direccion,numero,esChungo,idpersona);
            cargarTablaPersonas();
            cargarTablaVivienda();
            limpiarTexts();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una vivienda para modificar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonModificarViviendaActionPerformed

    private void botonListadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListadoActionPerformed
        try {
        // Obtener los nombres de la base de datos
        ResultSet resultSet = daopersonas.getPersonas();

        // Crear una lista para almacenar los nombres
        List<String> nombres = new ArrayList<>();

        // Agregar los nombres a la lista
        while (resultSet.next()) {
            String nombre = resultSet.getString("nombre");
            nombres.add(nombre);
        }

        // Ordenar la lista alfabéticamente
        Collections.sort(nombres);

        // Construir el String con los nombres ordenados
        StringBuilder sb = new StringBuilder();
        for (String nombre : nombres) {
            sb.append(nombre).append("\n");
        }

        // Mostrar el String en el TextArea
        lista.setText(sb.toString());
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al obtener los nombres", "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_botonListadoActionPerformed

    private void tablaPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPersonasMouseClicked
        int filaSeleccionada = tablaPersonas.getSelectedRow();
        if (filaSeleccionada != -1) {
            int idPersona = Integer.parseInt(tablaPersonas.getValueAt(filaSeleccionada, 0).toString());

            try {
                ResultSet resultSetVivienda = daopersonas.getViviendaPersona(idPersona);

                DefaultTableModel modeloVivienda = new DefaultTableModel();
                modeloVivienda.addColumn("ID");
                modeloVivienda.addColumn("DIRECCIÓN");
                modeloVivienda.addColumn("NUMERO");
                modeloVivienda.addColumn("ZONA PEGRILOSA");
                modeloVivienda.addColumn("ID PERSONA");
                // Añade más columnas según los datos que quieras mostrar de la vivienda

                while (resultSetVivienda.next()) {
                    Object[] fila = new Object[5]; // Ajusta el tamaño según el número de columnas
                    fila[0] = resultSetVivienda.getInt("idvivienda");
                    fila[1] = resultSetVivienda.getString("direccion");
                    fila[2] = resultSetVivienda.getInt("numero");
                    fila[3] = resultSetVivienda.getBoolean("esChungo");
                    fila[4] = resultSetVivienda.getInt("idpersona");
                    // Añade más elementos al arreglo según los datos que quieras mostrar de la vivienda

                    modeloVivienda.addRow(fila);
                }

                tablaVivienda.setModel(modeloVivienda);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error al cargar los datos de la vivienda", "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_tablaPersonasMouseClicked

    private void comboBoxPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboBoxPersonasMouseClicked
        int seleccionado = comboBoxPersonas.getSelectedIndex();
    }//GEN-LAST:event_comboBoxPersonasMouseClicked

    private void botonBorrarViviendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarViviendaActionPerformed
        int fila = tablaVivienda.getSelectedRow();
            if (fila != -1) {
                int id = Integer.parseInt(tablaVivienda.getValueAt(fila, 0).toString());
                String direccion = tablaVivienda.getValueAt(fila, 1).toString();
                int numero = Integer.parseInt(tablaVivienda.getValueAt(fila, 2).toString());
                boolean esChungo = Boolean.parseBoolean(tablaVivienda.getValueAt(fila, 3).toString());
                int idpersona = Integer.parseInt(tablaVivienda.getValueAt(fila, 4).toString());

                int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres borrar la vivienda?", "Confirmar Borrado", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                daopersonas.borrarVivienda(id, direccion,numero,esChungo,idpersona);
                cargarTablaPersonas();
                cargarTablaVivienda();
                limpiarTexts();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una categoría para borrar.", "Error", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_botonBorrarViviendaActionPerformed

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        int filaSeleccionada = tablaPersonas.getSelectedRow();
        if (filaSeleccionada != -1) {
            int idAnterior = Integer.parseInt(tablaPersonas.getValueAt(filaSeleccionada, 0).toString());
            int nuevoId = Integer.parseInt(textID.getText());
            String nombre = textNombre.getText();

            daopersonas.modificarPersona(idAnterior, nuevoId, nombre);
            cargarTablaPersonas();
            limpiarTexts();
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una persona para modificar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonInsertarViviendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInsertarViviendaActionPerformed
         String idvivienda = textIDVivienda.getText();
        try{
            if(idvivienda.isEmpty()) {
                throw new ExcepcionInsertVacio();
            } else{
                int id = Integer.parseInt(idvivienda);
                String direccion = textDireccion.getText();
                int numero = Integer.parseInt(textNumero.getText());
                boolean esChungo = Boolean.parseBoolean(textZonaChunga.getText());
                int idpersona = Integer.parseInt(textIDPersona1.getText());
                daopersonas.insertarVivienda(id, direccion, numero, esChungo,idpersona);
                cargarTablaVivienda();
                limpiarTexts();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());        
        }  
    }//GEN-LAST:event_botonInsertarViviendaActionPerformed

    private void botonNuevaVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaVentanaActionPerformed
        Prueba prueba = new Prueba();
        prueba.show();
    }//GEN-LAST:event_botonNuevaVentanaActionPerformed

    public void limpiarTexts(){
        textDireccion.setText("");
        textID.setText("");
        textIDPersona1.setText("");
        textIDVivienda.setText("");
        textNombre.setText("");
        textNumero.setText("");
        textZonaChunga.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBorrarVivienda;
    private javax.swing.JButton botonInsertar;
    private javax.swing.JButton botonInsertarVivienda;
    private javax.swing.JButton botonListado;
    private javax.swing.JButton botonModificar1;
    private javax.swing.JButton botonModificarVivienda;
    private javax.swing.JButton botonNuevaVentana;
    private javax.swing.JComboBox<String> comboBoxPersonas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea lista;
    private javax.swing.JTable tablaPersonas;
    private javax.swing.JTable tablaVivienda;
    private javax.swing.JTextField textDireccion;
    private javax.swing.JTextField textID;
    private javax.swing.JTextField textIDPersona1;
    private javax.swing.JTextField textIDVivienda;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textNumero;
    private javax.swing.JTextField textZonaChunga;
    // End of variables declaration//GEN-END:variables
}
