/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.repaso2recupspro;

import Conexion.BD1;
import DAOS.DAOCategoria;
import DAOS.DAOLibros;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anton
 */
public class Main extends javax.swing.JFrame {
    
     DAOLibros daolibros = new DAOLibros();
     DAOCategoria daocategoria = new DAOCategoria();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        cargarTablaCategoria();
        
        daolibros.cargarComboBox(comboBoxLibro);
        daocategoria.listadoOrdenado();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CategoriaTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        libroTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIDLibro = new javax.swing.JTextField();
        txtNombreLibro = new javax.swing.JTextField();
        comboBoxLibro = new javax.swing.JComboBox<>();
        buttonModificarCategoria = new javax.swing.JButton();
        buttonInsertarCategoria = new javax.swing.JButton();
        buttonBorrarCategoria = new javax.swing.JButton();
        buttonModificarLibro = new javax.swing.JButton();
        buttonInsertarLibro = new javax.swing.JButton();
        buttonBorrarLibro = new javax.swing.JButton();
        buttonDeshacerEliminadoCategoria = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CategoriaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CategoriaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriaTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CategoriaTable);

        libroTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(libroTable);

        jLabel1.setText("Nombre:");

        jLabel2.setText("ID:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("IdLibro:");

        buttonModificarCategoria.setText("Modificar");
        buttonModificarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarCategoriaActionPerformed(evt);
            }
        });

        buttonInsertarCategoria.setText("Insertar");
        buttonInsertarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertarCategoriaActionPerformed(evt);
            }
        });

        buttonBorrarCategoria.setText("Borrar");
        buttonBorrarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarCategoriaActionPerformed(evt);
            }
        });

        buttonModificarLibro.setText("Modificar");
        buttonModificarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonModificarLibroActionPerformed(evt);
            }
        });

        buttonInsertarLibro.setText("Insertar");
        buttonInsertarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertarLibroActionPerformed(evt);
            }
        });

        buttonBorrarLibro.setText("Borrar");
        buttonBorrarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBorrarLibroActionPerformed(evt);
            }
        });

        buttonDeshacerEliminadoCategoria.setText("Deshacer Eliminado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(635, 635, 635))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(680, 680, 680))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(buttonDeshacerEliminadoCategoria))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel4))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonModificarLibro)
                                    .addComponent(buttonInsertarLibro, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonBorrarLibro, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buttonModificarCategoria)
                                    .addComponent(buttonBorrarCategoria)))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(863, Short.MAX_VALUE)
                    .addComponent(buttonInsertarCategoria)
                    .addGap(338, 338, 338)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(buttonModificarCategoria)
                                .addGap(18, 18, 18)
                                .addComponent(buttonBorrarCategoria)
                                .addGap(18, 18, 18)
                                .addComponent(buttonDeshacerEliminadoCategoria)))
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonInsertarLibro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonModificarLibro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonBorrarLibro))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombreLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBoxLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(124, 124, 124))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(buttonInsertarCategoria)
                    .addContainerGap(401, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CategoriaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriaTableMouseClicked
        cargarTablaLibros();
    }//GEN-LAST:event_CategoriaTableMouseClicked

    private void buttonInsertarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertarCategoriaActionPerformed
        int id = Integer.parseInt(txtID.getText());
        String nombre = txtNombre.getText();
        
        daocategoria.insertarCategoria(id, nombre);
        cargarTablaCategoria();
    }//GEN-LAST:event_buttonInsertarCategoriaActionPerformed

    private void buttonBorrarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarCategoriaActionPerformed
    int fila = CategoriaTable.getSelectedRow();
            if (fila != -1) {
                int id = Integer.parseInt(CategoriaTable.getValueAt(fila, 0).toString());
                String nombre = CategoriaTable.getValueAt(fila, 1).toString();

                int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres borrar la categoría?", "Confirmar Borrado", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                daocategoria.borrarCategoria(id, nombre);
                cargarTablaCategoria();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona una categoría para borrar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonBorrarCategoriaActionPerformed

    private void buttonModificarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarCategoriaActionPerformed
        int id = Integer.parseInt(txtID.getText());
        String nombre = txtNombre.getText();
        
        daocategoria.modificarCategoria(id, nombre);
        cargarTablaCategoria();
    }//GEN-LAST:event_buttonModificarCategoriaActionPerformed

    private void buttonInsertarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertarLibroActionPerformed
    String idLibroText = txtIDLibro.getText();
    String nombreLibro = txtNombreLibro.getText();
    int categoria = comboBoxLibro.getSelectedIndex()+1;

        if (!idLibroText.isEmpty() && !nombreLibro.isEmpty()) {
            try {
                int idLibro = Integer.parseInt(idLibroText);
                daolibros.insertarLibro(idLibro, nombreLibro, categoria);
                cargarTablaLibros();
            } catch (NumberFormatException e) {
                System.out.println("Error al convertir a entero: " + e.getMessage());
            }
        } else {
            System.out.println("Los campos ID del libro y Nombre del libro no pueden estar vacíos");
        }
    }//GEN-LAST:event_buttonInsertarLibroActionPerformed

    private void buttonBorrarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBorrarLibroActionPerformed
    int fila = libroTable.getSelectedRow();
        if (fila != -1) {
            int id = Integer.parseInt(libroTable.getValueAt(fila, 0).toString());
            String nombre = libroTable.getValueAt(fila, 1).toString();
            int categoria = Integer.parseInt(libroTable.getValueAt(fila, 0).toString());

            int confirmacion = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres borrar el libro?", "Confirmar Borrado", JOptionPane.YES_NO_OPTION);

            if (confirmacion == JOptionPane.YES_OPTION) {
                daolibros.borrarLibros(id, nombre, categoria);
                cargarTablaLibros();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un libro para borrar.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonBorrarLibroActionPerformed

    private void buttonModificarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarLibroActionPerformed
        int id = Integer.parseInt(txtIDLibro.getText());
        String nombre = txtNombreLibro.getText();
         int categoria = comboBoxLibro.getSelectedIndex()+1;
        
        daolibros.modificarLibros(id, nombre,categoria);
        cargarTablaLibros();
    }//GEN-LAST:event_buttonModificarLibroActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void cargarTablaLibros(){
        try{
            ResultSet resultset = daolibros.getLibros();

        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        modelo.addColumn("Categoria");
        
        Object[] registroLeido = new Object[3];
        while(resultset.next()) {
            registroLeido[0] = resultset.getInt("idLibros");
            registroLeido[1] = resultset.getString("nombre");
            registroLeido[2] = resultset.getString("categoria");
                        
            modelo.addRow(registroLeido);
        }
        libroTable.setModel(modelo);
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }
    
    public void cargarTablaCategoria() {
         try{
             ResultSet resultset = daocategoria.getCategoria();

        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Id");
        modelo.addColumn("Nombre");
        
        Object[] registroLeido = new Object[2];
        while(resultset.next()) {
            registroLeido[0] = resultset.getInt("id");
            registroLeido[1] = resultset.getString("nombre");
                        
            modelo.addRow(registroLeido);
        }
        CategoriaTable.setModel(modelo);
         }catch(Exception e){
             e.printStackTrace();
         }
        
    }
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CategoriaTable;
    private javax.swing.JButton buttonBorrarCategoria;
    private javax.swing.JButton buttonBorrarLibro;
    private javax.swing.JButton buttonDeshacerEliminadoCategoria;
    private javax.swing.JButton buttonInsertarCategoria;
    private javax.swing.JButton buttonInsertarLibro;
    private javax.swing.JButton buttonModificarCategoria;
    private javax.swing.JButton buttonModificarLibro;
    private javax.swing.JComboBox<String> comboBoxLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable libroTable;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDLibro;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreLibro;
    // End of variables declaration//GEN-END:variables
}
