/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import DAOS.Alumno;
import DAOS.DAOAlumno;
import DAOS.DAOColegio;
import com.mysql.cj.conf.PropertyKey;
import java.awt.List;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anton
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    DAOAlumno daoAlumno = new DAOAlumno();
    DAOColegio daoColegio = new DAOColegio();
    int codigoColegioEliminado;
    String nombreColegioEliminado;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        cargarTablaColegio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaColegio = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaAlumnos = new javax.swing.JTable();
        buttonDeshacer = new javax.swing.JButton();
        buttonOrdenar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        buttonComprobar = new javax.swing.JButton();
        textCodigoColegio = new javax.swing.JTextField();
        textNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CheckBoxFeo = new javax.swing.JCheckBox();
        buttonAgregar = new javax.swing.JButton();
        textEdad1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaColegio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaColegio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaColegioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaColegio);

        tablaAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaAlumnos);

        buttonDeshacer.setText(" Deshacer Colegio Eliminado");
        buttonDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeshacerActionPerformed(evt);
            }
        });

        buttonOrdenar.setText("Ordenar Colegios");

        buttonEliminar.setText("Eliminar Colegio");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        buttonComprobar.setText("ComprobarAlumnosFeos");
        buttonComprobar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonComprobarActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel1");

        CheckBoxFeo.setText("Feo");

        buttonAgregar.setText("Agregar Alumno");
        buttonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 61, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonDeshacer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonOrdenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonComprobar, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(buttonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(103, 103, 103))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(128, 128, 128)
                                        .addComponent(CheckBoxFeo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(textCodigoColegio, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(694, 694, 694)
                                .addComponent(jLabel2)))
                        .addContainerGap(121, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(755, Short.MAX_VALUE)
                    .addComponent(buttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(104, 104, 104)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(766, Short.MAX_VALUE)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(118, 118, 118)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(776, Short.MAX_VALUE)
                    .addComponent(textEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(108, 108, 108)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(buttonDeshacer)
                        .addGap(18, 18, 18)
                        .addComponent(buttonOrdenar)
                        .addGap(18, 18, 18)
                        .addComponent(buttonComprobar)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textCodigoColegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CheckBoxFeo)
                        .addGap(44, 44, 44)
                        .addComponent(buttonAgregar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addComponent(buttonEliminar)
                    .addContainerGap(502, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(298, Short.MAX_VALUE)
                    .addComponent(textNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(248, 248, 248)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(335, Short.MAX_VALUE)
                    .addComponent(textEdad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(211, 211, 211)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarActionPerformed
        int codigoColegio = Integer.parseInt(textCodigoColegio.getText());
        String nombre = textNombre.getText();
        int edad = Integer.parseInt(textEdad1.getText());
        boolean feo = CheckBoxFeo.isSelected();
        
        daoAlumno.InsertarAlumno(codigoColegio, nombre, edad, feo);
    }//GEN-LAST:event_buttonAgregarActionPerformed

    private void tablaColegioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaColegioMouseClicked
        cargarTablaAlumnos();
    }//GEN-LAST:event_tablaColegioMouseClicked

    private void buttonComprobarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonComprobarActionPerformed
        int fila = tablaColegio.getSelectedRow();
        int codigoColegio = Integer.parseInt(tablaColegio.getValueAt(fila, 0).toString());
        
        if(daoAlumno.ComprobarAlumnosFeos(codigoColegio)){
            JOptionPane.showMessageDialog(this, "Hay feo");
        }else{
            JOptionPane.showMessageDialog(this, " No hay feo");
        }
    }//GEN-LAST:event_buttonComprobarActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        int fila = tablaColegio.getSelectedRow();
        int codigoColegio = Integer.parseInt(tablaColegio.getValueAt(fila, 0).toString());
        String nombre = tablaColegio.getValueAt(fila, 1).toString();
        codigoColegioEliminado = codigoColegio;
        nombreColegioEliminado = nombre;
        daoColegio.EliminarColegio(codigoColegio);
        cargarTablaColegio();
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void buttonDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeshacerActionPerformed
      
        daoColegio.DeshacerColegioEliminado(codigoColegioEliminado, nombreColegioEliminado);
        cargarTablaColegio();
    }//GEN-LAST:event_buttonDeshacerActionPerformed

    public void cargarTablaAlumnos(){
        try{
            int fila = tablaColegio.getSelectedRow();
            int codigoColegio = Integer.parseInt(tablaColegio.getValueAt(fila, 0).toString());
            ResultSet resultset = daoAlumno.getAlumnos(codigoColegio);

        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Código Colegio");
        modelo.addColumn("Nombre");
        modelo.addColumn("Edad");
        modelo.addColumn("Feo");
        
        Object[] registroLeido = new Object[4];
        while(resultset.next()) {
            registroLeido[0] = resultset.getInt("idColegio");
            registroLeido[1] = resultset.getString("nombre");
            registroLeido[2] = resultset.getInt("edad");
            registroLeido[3] = resultset.getBoolean("feo");
                        
            modelo.addRow(registroLeido);
        }
        tablaAlumnos.setModel(modelo);
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }
    
     public void cargarTablaColegio() {
         try{
             ResultSet resultset = daoColegio.getColegio();

        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        
        Object[] registroLeido = new Object[2];
        while(resultset.next()) {
            registroLeido[0] = resultset.getInt("idColegio");
            registroLeido[1] = resultset.getString("nombre");
                        
            modelo.addRow(registroLeido);
        }
        tablaColegio.setModel(modelo);
         }catch(Exception e){
             e.printStackTrace();
         }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    new VentanaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckBoxFeo;
    private javax.swing.JButton buttonAgregar;
    private javax.swing.JButton buttonComprobar;
    private javax.swing.JButton buttonDeshacer;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonOrdenar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaAlumnos;
    private javax.swing.JTable tablaColegio;
    private javax.swing.JTextField textCodigoColegio;
    private javax.swing.JTextField textEdad1;
    private javax.swing.JTextField textNombre;
    // End of variables declaration//GEN-END:variables
}
